### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by fanatid**
Not sure, but think this will better. Feel free to drop or cherry pick any commit to master.

### CODE REVIEW

**Comment by jprichardson** [comment]
NACK on https://github.com/ExodusMovement/buffer-expand/pull/1/commits/9c8d71f277aca79f4385bc69eedb7f4ede0babbe and https://github.com/ExodusMovement/buffer-expand/pull/1/commits/9a456efeeb7dd4d191c0a58b2f71e90d5496abe7

The rest is good though.

**Comment by fanatid** [comment]
Why not use `randombytes`? (part of crypto-browserify)

**Comment by jprichardson** [comment]
> Why not use randombytes? (part of crypto-browserify)

This module exists to serve Exodus and secure-container. It's an unnecessary dependency. If someone wants to use it outside of Exodus or secure-container, they can just use browserify/crypto-browserify.

**Comment by RyanZim** [comment]
@jprichardson You keep posting what I'm going to say just ahead of me. :laughing:

**Comment by fanatid** [comment]
Okay, updated.

**Comment by jprichardson** [comment]
ACK

**Pull request merged**
